# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: melo_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='melo_rpc.proto',
  package='melo.rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0emelo_rpc.proto\x12\x08melo.rpc\"\x1f\n\x0cPauseRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\rPauseResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\" \n\rResumeRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"7\n\x0eResumeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x84\x01\n\x07MeloRpc\x12:\n\x05Pause\x12\x16.melo.rpc.PauseRequest\x1a\x17.melo.rpc.PauseResponse\"\x00\x12=\n\x06Resume\x12\x17.melo.rpc.ResumeRequest\x1a\x18.melo.rpc.ResumeResponse\"\x00\x62\x06proto3')
)




_PAUSEREQUEST = _descriptor.Descriptor(
  name='PauseRequest',
  full_name='melo.rpc.PauseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='melo.rpc.PauseRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=59,
)


_PAUSERESPONSE = _descriptor.Descriptor(
  name='PauseResponse',
  full_name='melo.rpc.PauseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='melo.rpc.PauseResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='melo.rpc.PauseResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=115,
)


_RESUMEREQUEST = _descriptor.Descriptor(
  name='ResumeRequest',
  full_name='melo.rpc.ResumeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='melo.rpc.ResumeRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=149,
)


_RESUMERESPONSE = _descriptor.Descriptor(
  name='ResumeResponse',
  full_name='melo.rpc.ResumeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='melo.rpc.ResumeResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='melo.rpc.ResumeResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['PauseRequest'] = _PAUSEREQUEST
DESCRIPTOR.message_types_by_name['PauseResponse'] = _PAUSERESPONSE
DESCRIPTOR.message_types_by_name['ResumeRequest'] = _RESUMEREQUEST
DESCRIPTOR.message_types_by_name['ResumeResponse'] = _RESUMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PauseRequest = _reflection.GeneratedProtocolMessageType('PauseRequest', (_message.Message,), dict(
  DESCRIPTOR = _PAUSEREQUEST,
  __module__ = 'melo_rpc_pb2'
  # @@protoc_insertion_point(class_scope:melo.rpc.PauseRequest)
  ))
_sym_db.RegisterMessage(PauseRequest)

PauseResponse = _reflection.GeneratedProtocolMessageType('PauseResponse', (_message.Message,), dict(
  DESCRIPTOR = _PAUSERESPONSE,
  __module__ = 'melo_rpc_pb2'
  # @@protoc_insertion_point(class_scope:melo.rpc.PauseResponse)
  ))
_sym_db.RegisterMessage(PauseResponse)

ResumeRequest = _reflection.GeneratedProtocolMessageType('ResumeRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESUMEREQUEST,
  __module__ = 'melo_rpc_pb2'
  # @@protoc_insertion_point(class_scope:melo.rpc.ResumeRequest)
  ))
_sym_db.RegisterMessage(ResumeRequest)

ResumeResponse = _reflection.GeneratedProtocolMessageType('ResumeResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESUMERESPONSE,
  __module__ = 'melo_rpc_pb2'
  # @@protoc_insertion_point(class_scope:melo.rpc.ResumeResponse)
  ))
_sym_db.RegisterMessage(ResumeResponse)



_MELORPC = _descriptor.ServiceDescriptor(
  name='MeloRpc',
  full_name='melo.rpc.MeloRpc',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=209,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='Pause',
    full_name='melo.rpc.MeloRpc.Pause',
    index=0,
    containing_service=None,
    input_type=_PAUSEREQUEST,
    output_type=_PAUSERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Resume',
    full_name='melo.rpc.MeloRpc.Resume',
    index=1,
    containing_service=None,
    input_type=_RESUMEREQUEST,
    output_type=_RESUMERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MELORPC)

DESCRIPTOR.services_by_name['MeloRpc'] = _MELORPC

# @@protoc_insertion_point(module_scope)
