#!/bin/sh
time=$(date "+%Y%m%d-%H%M%S")
touch /home/pi/share/raspi/python_log/log-$time.log 2>&1
/usr/bin/env python3 -u /home/pi/share/raspi/ui_client.py > /home/pi/share/raspi/python_log/log-$time.log 2>&1 &

