msg_to_tx2 = [
{'RASPI_IS_READY':True}, #0
{'MEETING_IS_STARTING':True}, #1
{'MEETING_IS_ENDING':True}, #2
{'MEETING_IS_PAUSING':True}, #3
{'MEETING_IS_RESUMING':True}, #4
{'ERROR_CODE':0}, #5
{'VOLUME_IS_UP':0}, #6
{'VOLUME_IS_DOWN':0}, #7
{'MUTE':True}, #8
{'UNMUTE':True}, #9
{'RESET_MEETING':False},#10
{'WIFI_RSSI':0},#11
]

msg_from_tx2 = {
'SYSTEM_IS_READY':False,
'MEETING_IS_RECORDING':False,
'MEETING_IS_PAUSED':False,
'MEETING_IS_RESUME':False,
'TX2_END_MEETING':False,
'MEETING_IS_END':False,
'ERROR_CODE':0,
'VOLUME_IS_UP':0,
'VOLUME_IS_DOWN':0,
'MUTE':False,
'UNMUTE':False, 
'RESET_MEETING':False,
'WIFI_RSSI':-1,
'tx2_state':'READY',
}

#根据不同状态机，响应不同消息
msg_list_filter={
'READY':['SYSTEM_IS_READY','ERROR_CODE','WIFI_RSSI','tx2_state',],
'IDLE':['ERROR_CODE','VOLUME_IS_UP','VOLUME_IS_DOWN','WIFI_RSSI','tx2_state',],
'START_LOADING':['MEETING_IS_RECORDING','ERROR_CODE','WIFI_RSSI','tx2_state',],
'RECORDING':['TX2_END_MEETING','ERROR_CODE','VOLUME_IS_UP','VOLUME_IS_DOWN','MUTE','UNMUTE','WIFI_RSSI','tx2_state',],
'PAUSED':['MEETING_IS_PAUSED','TX2_END_MEETING','MEETING_IS_END','ERROR_CODE','VOLUME_IS_UP','VOLUME_IS_DOWN','MUTE','UNMUTE','WIFI_RSSI','tx2_state',],
'END_LOADING':['MEETING_IS_END','ERROR_CODE','WIFI_RSSI','tx2_state',]
}